### ISSUE TITLE
Does this support IPV6?

### ISSUE THREAD

**Issue by pliablepixels** [FGasper/p5-Net-WebSocket#4]
Hi, thanks for your excellent library. I am using it to implement a web socket server. It seems it does not respond to IPV6 - would you know if anything needs to be done to support v6 or it should be transparent? The instantiation is here https://github.com/pliablepixels/zmeventserver/blob/master/zmeventnotification.pl#L1163

Both  IO:Socket::IP &  IO::Socket::INET6 are installed on the system. 

Thank you.

**Comment by FGasper** [comment]
Net::WebSocket is a different distribution from Net::WebSocket::Server. You’ll need to contact N::WS::Server’s maintainer to answer that.

As for Net::WebSocket itself, it doesn’t care about the transport layer, so you can definitely use IPv6. Net::WebSocket also optionally supports compression, which I don’t think N::WS::Server does.

**Comment by pliablepixels** [comment]
ah fair enough, thanks
