### ISSUE TITLE
MockReader dependancy

### ISSUE THREAD

**Issue by heiderich** [FGasper/p5-Net-WebSocket#5]
The examples in `demo/shell_server.pl` and `demo/wscat.pl` use `MockReader`. I cannot find this package on CPAN. It might be worthwhile to indicate where it can be obtained.

**Comment by FGasper** [comment]
Oops! I had neglected to add this to the repo.

Fixed in 1a0feb8.

**Comment by heiderich** [comment]
This was fast. Thank you!
